CREATE DATABASE IF NOT EXISTS streamingdb;
USE streamingdb;

CREATE TABLE IF NOT EXISTS USUARIO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    data_cadastro DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS PERFIL (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome_perfil VARCHAR(255) UNIQUE NOT NULL,
    usuario_id INT NOT NULL,
    FOREIGN KEY (usuario_id) REFERENCES USUARIO(id)
);

CREATE TABLE IF NOT EXISTS CATEGORIA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS VIDEO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) UNIQUE NOT NULL,
    descricao VARCHAR(1000),
    duracao INT NOT NULL,
    categoria_id INT NOT NULL,
    FOREIGN KEY (categoria_id) REFERENCES CATEGORIA(id)
);

CREATE TABLE IF NOT EXISTS VISUALIZACAO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    perfil_id INT NOT NULL,
    video_id INT NOT NULL,
    data_hora DATETIME NOT NULL,
    progresso INT NOT NULL,
    FOREIGN KEY (perfil_id) REFERENCES PERFIL(id),
    FOREIGN KEY (video_id) REFERENCES VIDEO(id)
);

CREATE TABLE IF NOT EXISTS AVALIACAO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    perfil_id INT NOT NULL,
    video_id INT NOT NULL,
    nota INT NOT NULL,
    comentario TEXT,
    FOREIGN KEY (perfil_id) REFERENCES PERFIL(id),
    FOREIGN KEY (video_id) REFERENCES VIDEO(id)
);
